sudo: false
language: generic

cache:
  apt: true

matrix:
  include:
    - addons:
        apt:
          packages: g++-7.3.0
          sources: ubuntu-toolchain-r-test

script:
  - make
  - ./sh/bin/ax_tests.exe
