#ifndef AX_LIB_AX_HPP
#define AX_LIB_AX_HPP

#include "algebraic.hpp"
#include "core.hpp"
#include "../../hpp/ax/hash.hpp"
#include "../../hpp/ax/logging.hpp"
#include "../../hpp/ax/string.hpp"
#include "../../hpp/ax/vector.hpp"
#include "../../hpp/ax/id.hpp"
#include "../../hpp/ax/option.hpp"
#include "../../hpp/ax/either.hpp"
#include "../../hpp/ax/choice.hpp"
#include "../../hpp/ax/pair.hpp"
#include "../../hpp/ax/record.hpp"
#include "../../hpp/ax/name.hpp"
#include "../../hpp/ax/castable.hpp"
#include "../../hpp/ax/field.hpp"
#include "../../hpp/ax/type.hpp"
#include "../../hpp/ax/inspectable.hpp"
#include "../../hpp/ax/type_descriptor.hpp"
#include "../../hpp/ax/type_descriptors.hpp"
#include "../../hpp/ax/property.hpp"
#include "../../hpp/ax/symbol.hpp"
#include "../../hpp/ax/parser.hpp"
#include "../../hpp/ax/mailbox.hpp"
#include "../../hpp/ax/address.hpp"
#include "../../hpp/ax/addressable.hpp"
#include "../../hpp/ax/event.hpp"
#include "../../hpp/ax/subscription.hpp"
#include "../../hpp/ax/eventable.hpp"

#endif
